# Generated by Django 5.0.6 on 2024-07-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='image',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
