# Generated by Django 5.0.6 on 2024-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_productomodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
